### ISSUE TITLE
element-ui 行内表单样式问题

### ISSUE THREAD

**Issue by belier-cn** [xaboy/form-create#204]
1.0.10

element-ui 2.13.1

![image](https://user-images.githubusercontent.com/41943291/79723734-d8ebb080-8318-11ea-80c2-dd189e865fc3.png)

代码示例：https://jsrun.net/fAfKp

原因：
![image](https://user-images.githubusercontent.com/41943291/79723907-33850c80-8319-11ea-9a95-598990797bf1.png)

**Comment by xaboy** [comment]
兼容性问题,下个版本我优化一下. 你可以先手动加下面得样式兼容一下
```css
.form-create.el-form--inline .el-form-item__label {
    display: -webkit-box;
    float: left;
}
```
